// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SolidConsoleStorage.Models;
using System;

namespace SolidConsoleStorage.Migrations
{
    [DbContext(typeof(StorageContext))]
    partial class StorageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolidConsoleStorage.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDelivery");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("SolidConsoleStorage.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("UnitId");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.HasIndex("UnitId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SolidConsoleStorage.Models.ProductBatch", b =>
                {
                    b.Property<int>("ProductId");

                    b.Property<int>("BatchId");

                    b.Property<double>("Quantity");

                    b.HasKey("ProductId", "BatchId");

                    b.HasIndex("BatchId");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("SolidConsoleStorage.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UnitName");

                    b.HasKey("Id");

                    b.HasIndex("UnitName")
                        .IsUnique()
                        .HasFilter("[UnitName] IS NOT NULL");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("SolidConsoleStorage.Models.Product", b =>
                {
                    b.HasOne("SolidConsoleStorage.Models.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SolidConsoleStorage.Models.ProductBatch", b =>
                {
                    b.HasOne("SolidConsoleStorage.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SolidConsoleStorage.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
